### PR TITLE
Implement Parallel[Task, ParallelTask] instance

### PR DESCRIPTION
**Pull request by joroKr21**
Also forward test equality for `Task` to `IO` which calls
`TestContext.tick` and handles non-terminating tests properly.

### CODE REVIEW

**Comment by joroKr21** [comment]
Ugh, what was the magic flag to get SAM on 2.11?

**Comment by ChristopherDavenport** [comment]
I think we need to law check the applicative instance of ParallelTask.

**Comment by joroKr21** [comment]
> I think we need to law check the applicative instance of ParallelTask.

Hmm, should we pull this instance out in `TaskInstances` so it's visible for general use?

**Comment by ChristopherDavenport** [comment]
My inclination is yes, that should be public. If it already has an Applicative instance in scalaz then that could cause conflicts for users with older shims and we should instead opt for package private. Still testable, but not exposed.

**Comment by joroKr21** [comment]
Ah I think I didn't understand you. I made the applicative instance public but you meant it should be package private right?

**Comment by ChristopherDavenport** [comment]
Yeah, I don't want it to conflict with anything that shims core natively introduces in case people are using the two together for the base types.

So if we can make the package private then this is good to go.

**Comment by joroKr21** [comment]
I made it protected. Users can choose to expose it if they want by inheriting `TaskInstances`. Another option would to make it public but not implicit. I'm not sure.

**Review by ChristopherDavenport — APPROVED** [review]
Looks good to me. :+1:

**Pull request merged**
